roll.h
NAME
roll.h - The main include file.
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <getopt.h>
#include <errno.h>
#include <time.h>
#include <math.h>
#include <limits.h>
#include 'config.h'
Data Structures
struct ir_node
node of the intermediate representation parse tree
Macros
#define EXPRESSION_SIZE 1024
#define FALSE 0
#define HUNDRED -1
#define OP_DICE 4
#define OP_DIV 3
#define OP_GE 10
#define OP_GT 9
#define OP_HIGH 7
#define OP_LE 12
#define OP_LOW 8
#define OP_LT 11
#define OP_MINUS 6
#define OP_NE 13
#define OP_NUMBER 1
#define OP_PLUS 5
#define OP_REP 14
#define OP_TIMES 2
#define srandomdev() srand((unsigned) time(NULL))
#define TRUE 1
Functions
struct ir_node * allocate_node (void)
Allocates a new IR node.
void error (char *message)
Prints the specified error message and exits with a failure status.
struct ir_node * new_dice (struct ir_node *sides)
Allocates a new DICE node.
struct ir_node * new_number (int number)
Allocates a new NUMBER node.
struct ir_node * new_op (unsigned short int op, struct ir_node *left, struct ir_node *right)
Allocates a new OP node.
int roll (int dice)
Rolls an n-sided dice.
int roll_expression (struct ir_node *node, int print)
Roll dices and compute expressions.
void usage ()
Prints the program's usage.
Detailed Description
The main include file.
Author:
Matteo Corti
Definition in file roll.h.
Macro Definition Documentation
#define EXPRESSION_SIZE 1024
Todo
The maximum expression length should be dynamic
Maximum expression length
Definition at line 40 of file roll.h.
Referenced by main().
#define FALSE 0
Boolean false
Definition at line 33 of file roll.h.
Referenced by roll_expression().
#define HUNDRED -1
Constant representing a 1d100 rolled with 1d10 for the units and 1d10 for the tens
Definition at line 45 of file roll.h.
Referenced by roll_dice().
#define OP_DICE 4
N-sided dice node
Definition at line 83 of file roll.h.
Referenced by new_dice(), and roll_expression().
#define OP_DIV 3
Integer division node
Definition at line 82 of file roll.h.
Referenced by roll_expression().
#define OP_GE 10
Keep results greater or equal than
Definition at line 89 of file roll.h.
Referenced by roll_expression().
#define OP_GT 9
Keep results greater than
Definition at line 88 of file roll.h.
Referenced by roll_expression().
#define OP_HIGH 7
Keep highest results node
Definition at line 86 of file roll.h.
Referenced by roll_expression().
#define OP_LE 12
Keep results less or equal than
Definition at line 91 of file roll.h.
Referenced by roll_expression().
#define OP_LOW 8
Keep lowest resutls node
Definition at line 87 of file roll.h.
Referenced by roll_expression().
#define OP_LT 11
Keep results less than
Definition at line 90 of file roll.h.
Referenced by roll_expression().
#define OP_MINUS 6
Subtraction node
Definition at line 85 of file roll.h.
Referenced by roll_expression().
#define OP_NE 13
Keep results different from
Definition at line 92 of file roll.h.
Referenced by roll_expression().
#define OP_NUMBER 1
Number node
Definition at line 80 of file roll.h.
Referenced by new_number(), and roll_expression().
#define OP_PLUS 5
Addition node
Definition at line 84 of file roll.h.
Referenced by roll_expression().
#define OP_REP 14
Number of rolls (repetitions)
Definition at line 93 of file roll.h.
Referenced by roll_expression().
#define OP_TIMES 2
Multiplication node
Definition at line 81 of file roll.h.
Referenced by roll_expression().
#define srandomdev() srand((unsigned) time(NULL))
defines srandomdev usig srand of the current time if srandomdev and getpid are missing
Definition at line 72 of file roll.h.
Referenced by main().
#define TRUE 1
Boolean true
Definition at line 28 of file roll.h.
Referenced by main(), and roll_expression().
Function Documentation
struct ir_node* allocate_node (void)
Allocates a new IR node.
Returns:
Newly allocated node
Definition at line 266 of file roll.c.
References error(), ir_node::left, ir_node::next, ir_node::op, ir_node::right, and ir_node::value.
Referenced by new_dice(), new_number(), and new_op().
                                         {
  struct ir_node * node = malloc(sizeof(struct ir_node));
  if (node == NULL) {
    error("Out of memory\n");
    exit(EXIT_FAILURE);
  }
  /* initialize default values */
  node->left = NULL;
  node->right = NULL;
  node->next = NULL;
  node->op = 0;
  node->value = 0;
  
  return node;
  
}
void error (char * message)
Prints the specified error message and exits with a failure status.
Parameters:
Definition at line 50 of file roll.c.
Referenced by allocate_node(), main(), and roll_expression().
                           {
  fprintf(stderr, "\nError: %s\n", message);
  exit(EXIT_FAILURE);
}
struct ir_node* new_dice (struct ir_node * sides)
Allocates a new DICE node.
Parameters:
Definition at line 344 of file roll.c.
References allocate_node(), ir_node::op, OP_DICE, ir_node::right, and ir_node::value.
                                                    {
  
  struct ir_node * node = allocate_node();
  node->op = OP_DICE;
  node->value = 0;
  node->right = sides;
  return node;
  
}
struct ir_node* new_number (int number)
Allocates a new NUMBER node.
Parameters:
Definition at line 290 of file roll.c.
References allocate_node(), ir_node::op, OP_NUMBER, and ir_node::value.
                                           {
  struct ir_node * node = allocate_node();
  node->op = OP_NUMBER;
  node->value = number;
  return node;
}
struct ir_node* new_op (unsigned short int op, struct ir_node * left, struct ir_node * right)
Allocates a new OP node.
Parameters:
Definition at line 328 of file roll.c.
References allocate_node(), ir_node::left, ir_node::op, ir_node::right, and ir_node::value.
                                                                                                {
  struct ir_node * node = allocate_node();
  node->op = op;
  node->value = 0;
  node->left = left;
  node->right = right;
  return node;
  
}
int roll (int dice)
Rolls an n-sided dice.
Parameters:
Definition at line 124 of file roll.c.
Referenced by roll_dice().
                   {
  /*
   * In: W. H. Press et al,Numerical Recipes in C: The Art of
   * Scientific Computing. New York, Cambridge University Press,
   * 1992, 2nd ed., p. 277
   *
   * "If you want to generate a random integer between 1
   * and 10, you should always do it by using high-order
   * bits, as in
   *
   * j=1+(int) (10.0*rand()/(RAND_MAX+1.0));
   */
  int res = 1+(int)(((double)dice)*random()/(RAND_MAX+1.0));
  return res;
}
int roll_expression (struct ir_node * node, int print)
Roll dices and compute expressions.
Parameters:
Definition at line 376 of file roll.c.
References compare(), error(), FALSE, ir_node::left, ir_node::next, ir_node::op, OP_DICE, OP_DIV, OP_GE, OP_GT, OP_HIGH, OP_LE, OP_LOW, OP_LT, OP_MINUS, OP_NE, OP_NUMBER, OP_PLUS, OP_REP, OP_TIMES, ir_node::right, roll_dice(), roll_expression(), TRUE, and ir_node::value.
Referenced by roll_expression().
                                                         {
  int high;
  int i;
  int limit;
  int low;
  int repetitions;
  int return_value = 0;
  int sides;
  int tmp;
  int * results;
  struct ir_node * cur;
  cur = node;
  while (cur != NULL) {
    int sum = 0;
    switch (cur->op) {
    
    case OP_NUMBER:
      sum = cur->value;
      break;
    case OP_REP:
      for (i = 0; i < roll_expression(cur->left, FALSE); i++) {
        sum = checked_sum( sum, roll_expression(cur->right, FALSE) );
      }
      break;
      
    case OP_DICE:
      sum = roll_dice( roll_expression(cur->right, FALSE) );
      break;
      
    case OP_PLUS:
      sum = checked_sum( roll_expression( cur->left, FALSE ),
                         roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_MINUS:
      sum = checked_sum( roll_expression( cur->left, FALSE ),
                         -roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_TIMES:
      sum = checked_multiplication( roll_expression( cur->left, FALSE ),
                                   roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_DIV:
      sum = (int)
        ceil( (float)roll_expression( cur->left, FALSE ) /
              roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_HIGH:
      sides = roll_expression(cur->right->right->right, FALSE);
      repetitions = roll_expression(cur->right->left, FALSE);
      high = roll_expression(cur->left, FALSE);
      /* array to store the results to sort */
      if (!(results = malloc(sizeof(int)*repetitions))) {
        error("Out of memory");
      }
      
      for(i=0; i<repetitions; i++) {
        results[i] = roll_dice(sides);
      }
      qsort(results, repetitions, sizeof(int), &compare);
      for(i=(repetitions-high); i<repetitions; i++) {
        sum = checked_sum( sum, results[i] );
      }
      
      free(results);
      
      break;
      
    case OP_LOW:
      
      sides = roll_expression(cur->right->right->right, FALSE);
      repetitions = roll_expression(cur->right->left, FALSE);
      low = roll_expression(cur->left, FALSE);
      
      if (cur->right->left != NULL) {
        repetitions = roll_expression(cur->right->left, FALSE);
      }
                  
      /* array to store the results to sort */
      if (!(results = malloc(sizeof(int)*repetitions))) {
        error("Out of memory");
      }
      
      for(i=0; i<repetitions; i++) {
        results[i] = roll_dice(sides);
      }
      qsort(results, repetitions, sizeof(int), &compare);
      for(i=0; i<low; i++) {
        sum = checked_sum( sum, results[i] );
      }
      
      free(results);
      
      break;
    case OP_GT:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp <= limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_GE:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp < limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_LT:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp >= limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_LE:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp > limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_NE:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp == limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    default :
      
      fprintf(stderr, "Implementation error: unkown IR node with code %i\n", cur->op);
      exit(EXIT_FAILURE);
      
    }
    return_value = checked_sum( return_value, sum);
    if (print == TRUE) {
      printf("%i\n", sum);
    }
    
    cur = cur->next;
    
  }
  return return_value;
  
}
Author
Generated automatically by Doxygen for roll from the source code.