roll.c
NAME
roll.c - The main application file.
SYNOPSIS
#include 'roll.h'
Functions
struct ir_node * allocate_node (void)
Allocates a new IR node.
int compare (const void *p1, const void *p2)
Comparison function for qsort.
void error (char *message)
Prints the specified error message and exits with a failure status.
int main (int argc, char **argv)
Main program.
struct ir_node * new_dice (struct ir_node *sides)
Allocates a new DICE node.
struct ir_node * new_number (int number)
Allocates a new NUMBER node.
struct ir_node * new_op (unsigned short int op, struct ir_node *left, struct ir_node *right)
Allocates a new OP node.
int roll (int dice)
Rolls an n-sided dice.
int roll_dice (int sides)
Wrapper for roll(int dice) translates special dices (e.g., d%)
int roll_expression (struct ir_node *node, int print)
Roll dices and compute expressions.
void usage ()
Prints the program's usage.
Variables
int positive_flag
int sum_flag = FALSE
static int verbose_flag = FALSE
static int version_flag = FALSE
Detailed Description
The main application file.
Author:
Matteo Corti
Definition in file roll.c.
Function Documentation
struct ir_node* allocate_node (void)
Allocates a new IR node.
Returns:
Newly allocated node
Definition at line 266 of file roll.c.
References error(), ir_node::left, ir_node::next, ir_node::op, ir_node::right, and ir_node::value.
Referenced by new_dice(), new_number(), and new_op().
                                         {
  struct ir_node * node = malloc(sizeof(struct ir_node));
  if (node == NULL) {
    error("Out of memory\n");
    exit(EXIT_FAILURE);
  }
  /* initialize default values */
  node->left = NULL;
  node->right = NULL;
  node->next = NULL;
  node->op = 0;
  node->value = 0;
  
  return node;
  
}
int compare (const void * p1, const void * p2)
Comparison function for qsort.
Parameters:
Definition at line 306 of file roll.c.
Referenced by roll_expression().
                                              {
  const int i1 = *((const int *)p1);
  const int i2 = *((const int *)p2);
  if (i1 > i2) {
    return 1;
  } else if (i1 < i2) {
    return -1;
  } else {
    return 0;
  }
  
}
void error (char * message)
Prints the specified error message and exits with a failure status.
Parameters:
Definition at line 50 of file roll.c.
Referenced by allocate_node(), main(), and roll_expression().
                           {
  fprintf(stderr, "\nError: %s\n", message);
  exit(EXIT_FAILURE);
}
int main (int argc, char ** argv)
Main program.
Parameters:
Definition at line 150 of file roll.c.
References error(), EXPRESSION_SIZE, positive_flag, srandomdev, sum_flag, TRUE, usage(), verbose_flag, and version_flag.
                                {
  char expression[EXPRESSION_SIZE];
  int expression_size;
  
  srandomdev();
     
  while (TRUE) {
    static struct option long_options[] = {
      {"sum-series", no_argument, NULL, 's'},
      {"positive", no_argument, NULL, 'p'},
      {"verbose", no_argument, NULL, 'v'},
      {"version", no_argument, &version_flag, TRUE},
      {"help", no_argument, NULL, 'h'},
#ifdef DEBUG
      {"debug", no_argument, NULL, 'd'},
#endif
      {NULL, 0, NULL, 0}
    };
    /* getopt_long stores the option index here. */
    int option_index = 0;
    int c;
    
#ifdef DEBUG
    c = getopt_long (argc, argv, "hvspd",
             long_options, &option_index);
#else
    c = getopt_long (argc, argv, "hvsp",
             long_options, &option_index);
#endif
    
    /* Detect the end of the options. */
    if (c == -1)
      break;
     
    switch (c) {
    case 'v':
      verbose_flag = TRUE;
      break;
    case 's':
      sum_flag = TRUE;
      break;
      
    case 'p':
      positive_flag = TRUE;
      break;
    case 'h':
      usage();
      exit(0);
    case '?':
      usage();
      /* getopt_long already printed an error message. */
      exit(EXIT_SUCCESS);
#ifdef DEBUG
    case 'd':
      debug_flag++;
      break;
#endif
      
    case 0:
      break;
    default:
      abort ();
    }
  }
  if (version_flag) {
    printf("%s %s\n", PACKAGE_NAME, PACKAGE_VERSION);
    exit(EXIT_SUCCESS);
  }
  argc -= optind;
  argv += optind;
  
  /* build string to parse */
  expression[0] = '\0';
  expression_size = 0;
  while(argc>0) {
    expression_size += strlen(*argv);
    if (expression_size >= EXPRESSION_SIZE) {
      error("Expression too long!\n");
    }
    strncat(expression, *argv, EXPRESSION_SIZE-1);
    argc--;
    argv++;
  }
  
  if (expression_size > 0) {
    
    yy_scan_string(expression);
    yyparse();
  } else {
    error("No expression provided!\nPlease use the \"-h\" option.\n");
    exit(EXIT_FAILURE);
  }
  return 0;
}
struct ir_node* new_dice (struct ir_node * sides)
Allocates a new DICE node.
Parameters:
Definition at line 344 of file roll.c.
References allocate_node(), ir_node::op, OP_DICE, ir_node::right, and ir_node::value.
                                                    {
  
  struct ir_node * node = allocate_node();
  node->op = OP_DICE;
  node->value = 0;
  node->right = sides;
  return node;
  
}
struct ir_node* new_number (int number)
Allocates a new NUMBER node.
Parameters:
Definition at line 290 of file roll.c.
References allocate_node(), ir_node::op, OP_NUMBER, and ir_node::value.
                                           {
  struct ir_node * node = allocate_node();
  node->op = OP_NUMBER;
  node->value = number;
  return node;
}
struct ir_node* new_op (unsigned short int op, struct ir_node * left, struct ir_node * right)
Allocates a new OP node.
Parameters:
Definition at line 328 of file roll.c.
References allocate_node(), ir_node::left, ir_node::op, ir_node::right, and ir_node::value.
                                                                                                {
  struct ir_node * node = allocate_node();
  node->op = op;
  node->value = 0;
  node->left = left;
  node->right = right;
  return node;
  
}
int roll (int dice)
Rolls an n-sided dice.
Parameters:
Definition at line 124 of file roll.c.
Referenced by roll_dice().
                   {
  /*
   * In: W. H. Press et al,Numerical Recipes in C: The Art of
   * Scientific Computing. New York, Cambridge University Press,
   * 1992, 2nd ed., p. 277
   *
   * "If you want to generate a random integer between 1
   * and 10, you should always do it by using high-order
   * bits, as in
   *
   * j=1+(int) (10.0*rand()/(RAND_MAX+1.0));
   */
  int res = 1+(int)(((double)dice)*random()/(RAND_MAX+1.0));
  return res;
}
int roll_dice (int sides)
Wrapper for roll(int dice) translates special dices (e.g., d%)
Parameters:
Definition at line 59 of file roll.c.
References HUNDRED, roll(), and verbose_flag.
Referenced by roll_expression().
                         {
  int result = 0;
  
  if ( sides == HUNDRED ) {
    
    /* d100 -> d10*10+d10 */
    
    int d10 = roll(10);
    if (verbose_flag) {
      printf("d10 -> %i\n", d10);
    }
    d10 = d10 % 10;
    
    int d1 = roll(10);
    if (verbose_flag) {
      printf("d10 -> %i\n", d1);
    }
    
    if (d1 == 0 && d10 == 0) {
      result = 100;
    } else if (d10 == 0) {
      result = d1;
    } else {
      result = d10*10 + d1;
    }
  } else if ( sides == FUDGE_DICE ) {
    result = roll(3) - 2;
    if (verbose_flag) {
      switch (result) {
      case -1:
        printf("dF -> -\n");
        break;
      case 0:
        printf("dF -> o\n");
        break;
      case 1:
        printf("dF -> +\n");
        break;
      }
    }
    
  } else {
    result = roll(sides);
    
    if (verbose_flag) {
      printf("d%i -> %i\n", sides, result);
    }
  }
  return result;
  
}
int roll_expression (struct ir_node * node, int print)
Roll dices and compute expressions.
Parameters:
Definition at line 376 of file roll.c.
References compare(), error(), FALSE, ir_node::left, ir_node::next, ir_node::op, OP_DICE, OP_DIV, OP_GE, OP_GT, OP_HIGH, OP_LE, OP_LOW, OP_LT, OP_MINUS, OP_NE, OP_NUMBER, OP_PLUS, OP_REP, OP_TIMES, ir_node::right, roll_dice(), roll_expression(), TRUE, and ir_node::value.
Referenced by roll_expression().
                                                         {
  int high;
  int i;
  int limit;
  int low;
  int repetitions;
  int return_value = 0;
  int sides;
  int tmp;
  int * results;
  struct ir_node * cur;
  cur = node;
  while (cur != NULL) {
    int sum = 0;
    switch (cur->op) {
    
    case OP_NUMBER:
      sum = cur->value;
      break;
    case OP_REP:
      for (i = 0; i < roll_expression(cur->left, FALSE); i++) {
        sum = checked_sum( sum, roll_expression(cur->right, FALSE) );
      }
      break;
      
    case OP_DICE:
      sum = roll_dice( roll_expression(cur->right, FALSE) );
      break;
      
    case OP_PLUS:
      sum = checked_sum( roll_expression( cur->left, FALSE ),
                         roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_MINUS:
      sum = checked_sum( roll_expression( cur->left, FALSE ),
                         -roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_TIMES:
      sum = checked_multiplication( roll_expression( cur->left, FALSE ),
                                   roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_DIV:
      sum = (int)
        ceil( (float)roll_expression( cur->left, FALSE ) /
              roll_expression( cur->right, FALSE ) );
      break;
      
    case OP_HIGH:
      sides = roll_expression(cur->right->right->right, FALSE);
      repetitions = roll_expression(cur->right->left, FALSE);
      high = roll_expression(cur->left, FALSE);
      /* array to store the results to sort */
      if (!(results = malloc(sizeof(int)*repetitions))) {
        error("Out of memory");
      }
      
      for(i=0; i<repetitions; i++) {
        results[i] = roll_dice(sides);
      }
      qsort(results, repetitions, sizeof(int), &compare);
      for(i=(repetitions-high); i<repetitions; i++) {
        sum = checked_sum( sum, results[i] );
      }
      
      free(results);
      
      break;
      
    case OP_LOW:
      
      sides = roll_expression(cur->right->right->right, FALSE);
      repetitions = roll_expression(cur->right->left, FALSE);
      low = roll_expression(cur->left, FALSE);
      
      if (cur->right->left != NULL) {
        repetitions = roll_expression(cur->right->left, FALSE);
      }
                  
      /* array to store the results to sort */
      if (!(results = malloc(sizeof(int)*repetitions))) {
        error("Out of memory");
      }
      
      for(i=0; i<repetitions; i++) {
        results[i] = roll_dice(sides);
      }
      qsort(results, repetitions, sizeof(int), &compare);
      for(i=0; i<low; i++) {
        sum = checked_sum( sum, results[i] );
      }
      
      free(results);
      
      break;
    case OP_GT:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp <= limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_GE:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp < limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_LT:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp >= limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_LE:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp > limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    case OP_NE:
      
      limit = roll_expression(cur->right, FALSE);
      tmp = roll_expression(cur->left, FALSE);
      while (tmp == limit) {
        tmp = roll_expression(cur->left, FALSE);
      }
      sum = checked_sum( sum, tmp );
      
      break;
      
    default :
      
      fprintf(stderr, "Implementation error: unkown IR node with code %i\n", cur->op);
      exit(EXIT_FAILURE);
      
    }
    return_value = checked_sum( return_value, sum);
    if (print == TRUE) {
      printf("%i\n", sum);
    }
    
    cur = cur->next;
    
  }
  return return_value;
  
}
Variable Documentation
int positive_flag
command line argument: allow only positive results
Referenced by main().
int sum_flag = FALSE
command line argument: sum series
Definition at line 16 of file roll.c.
Referenced by main().
int verbose_flag = FALSE [static]
command line argument: verbose output
Definition at line 17 of file roll.c.
Referenced by main(), and roll_dice().
int version_flag = FALSE [static]
command line argument: version
Definition at line 18 of file roll.c.
Referenced by main().
Author
Generated automatically by Doxygen for roll from the source code.