name: Test

on:
  push:
    branches:
      - $default-branch
      - development
      - master
  # Run tests for any PRs
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    name: Running tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool pandoc

      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run the tests
        run:  |
          uname -a &&
          ./regen.sh &&
          ./configure &&
          make dist &&
          make check

  linux:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'debian:latest'
          - 'ubuntu:latest'
          - 'alpine:latest'
          - 'fedora:latest'
        include:        
          - distro: 'debian:latest'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install autoconf automake gcc make bison pandoc flex pkg-config
          - distro: 'ubuntu:latest'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install autoconf automake gcc make bison pandoc flex pkg-config
          - distro: 'alpine:latest'
            pre: >-
              apk update &&
              apk upgrade &&
              apk add -U bash &&
              apk add autoconf automake gcc binutils build-base bison flex pkgconfig
          - distro: 'fedora:latest'
            pre: >-
              dnf upgrade -y &&
              dnf install -y hostname &&
              dnf install -y autoconf automake gcc bison make flex pandoc

    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run the tests on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /roll -v ${PWD}:/roll ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && ./regen.sh \
              && ./configure \
              && make dist \
              && make check'

  rpm:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running RPM tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'fedora:39'
          - 'fedora:40'
        include:
          - distro: 'fedora:39'
            pre: >-
              dnf install -y autoconf automake rpm-build make gcc bison flex pandoc
          - distro: 'fedora:40'
            pre: >-
              dnf install -y autoconf automake rpm-build make gcc bison flex pandoc
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build the RPM on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /roll -v ${PWD}:/roll ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && ./regen.sh \
              && ./configure \
              && make rpm'
